name: Build Android gki Kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    outputs:
      BUILD_DATE: ${{ steps.generate-builddate.outputs.BUILDDATE }}
      KERNEL_VERSION: ${{ steps.generate-kernel.outputs.BUILDDATE }}
    steps:
      - name: Setup CCache
        uses: hendrikmuhs/ccache-action@v1.2
        
      - name: Set build Date
        id: generate-builddate
        run: echo "BUILDDATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      
      - name: Download prebuilt toolchain and Clone kernel source
        run: |
          sudo apt-get update
          sudo apt-get install -y git git-lfs zip
          
          mkdir -p ~/.bin
          PATH="${HOME}/.bin:${PATH}"
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          chmod a+rx ~/.bin/repo

          mkdir android_build
          cd android_build
          ~/.bin/repo init -u https://github.com/FlyLoongZ/android_gki_kernel_5.10_common -b repo_xml --git-lfs
          ~/.bin/repo sync
          
      - name: Build Kernel
        run: |
          export CC="ccache clang"
          export LTO=thin
          export BUILD_CONFIG=common/build.config.gki.aarch64
          build/build.sh

      - name: Read Kernel Version
        id: generate-kernel
        run: basename $(find ./out/android12-5.10/staging/lib/modules/ -name "*android12*") >> $GITHUB_OUTPUT
      
      - name: Package Kerenl
        run: |
          git clone --depth=1 https://github.com/FlyLoongZ/AnyKernel3
          cp out/android12-5.10/dist/Image AnyKernel3/Image
          zip -r9 AnyKernel3-${{ env.KERNEL_VERSION }}.zip AnyKernel3/* -x .git README.md
        
      - name: Upload AnyKernel3
        uses: actions/upload-artifact@v4
        with:
          name: Anykernel3-${{ env.KERNEL_VERSION }}
          path: Anykernel3/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.BUILD_DATE }}.${{ github.run_number }}
          files: "Anykernel3-${{ env.KERNEL_VERSION }}.zip"
          generate_release_notes: true

      
       
